baseURL = 'https://tailormyresume.io/'
languageCode = 'en-us'
title = 'Tailor My Resume'
theme = 'hugo-fresh'

[services]
  [services.googleAnalytics]
    id = 'G-KFYGS5Y77X'

# Main menu
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

# Footer
[params.footer]
  logo = "logo.svg"
  bulmalogo = false
  socialmediatitle = "Connect with us"
  
  [[params.footer.quicklinks]]
    title = "Legal"
    
    [[params.footer.quicklinks.links]]
      text = "Privacy Policy"
      link = "/privacy-policy"
      
    [[params.footer.quicklinks.links]]
      text = "Terms of Service"
      link = "/terms-of-service"
      
  [[params.footer.quicklinks]]
    title = "Company"
    
    [[params.footer.quicklinks.links]]
      text = "About"
      link = "/"
      
    [[params.footer.quicklinks.links]]
      text = "Contact"
      link = "mailto:aaron@tailormyresume.io"
      
    
  [[params.footer.socialmedia]]
    link = "https://linkedin.com/company/tailor-my-resume"
    icon = "linkedin"